<div style="padding-bottom: 20px;">
	<div class="main-teacher-page">
		<div>
			<h2 id="score"  style="color:white; font-weight:bolder; font-size:40pt; font-family: Arial, Helvetica, sans-serif;">Score</h2>
		</div>
		<form id="testCode">
			<div>
				<textarea id="codeSet1" name="codeSet1" rows="10" cols="70"> </textarea>
				<textarea id="codeSet2" name="codeSet2" rows="10" cols="70"> </textarea>
			</div>
			<div>
				<button class="btn btn-primary"  type="submit" style="background-color: black; border-color:white; color:white; font-weight:bolder; font-size:20pt; font-family: Arial, Helvetica, sans-serif;">Push To Test Code</button>
			</div>
		</form>
	</div>
</div>