<div class="body-container-wrapper">
    <div class="signup-background" style="background-image: url('../../../assets/img/yupp.jpg');">

        <div class="error-container col-lg-6 center" style="padding-top: 50px; padding-bottom: 120px">
            <div class="text-center">
                <form id="form-login" role="form" class="form-signin">
                    <h1 style="color: black; font-weight:bolder; padding-bottom: 5px">Welcome to iCheat</h1>
                    <h1 class="h3 mb-3 font-weight-normal" style="color: black;">Please sign in</h1>

                    <input type="text" name="username" id="username" class="form-control" placeholder="Email address" required="" autofocus="" style="margin-bottom: 5px;">
                    <label for="password" class="sr-only">Password</label>
                    <input type="password" id="password" name="password" class="form-control" placeholder="Password" required="">
                    <div class="checkbox mb-3">
                        <label>
                            <input type="checkbox" value="remember-me"> Remember me
                        </label>
                    </div>
                    <button class="btn btn-lg btn-primary btn-block" style="background-color: black; border-color:black;" type="submit">Sign in</button>
                </form>
            </div>
        </div>
    </div>
</div>