<div class="body-container-wrapper">
    <div class="signup-background" style="background-image: url('../../../assets/img/yupp.jpg');">
        <div class="body-container container-fluid">
            <div class="row-fluid-wrapper row-depth-1 row-number-1 ">
                <div class="row-fluid ">

                    <section>
                        <div class="input" style="margin-top:10px;">
                            <a href="/login" class="btn btn-primary float-right"
                                style="background-color: black; border-color:black;">Login</a>
                        </div>
                    </section>


                    <!-- Start of signup -->
                    <section class="products-background">
                        <section class="products-background">
                            <div class="span12 widget-span widget-type-cell">
                                <div class="hsg-page-width-normal text-center">
                                    <h1 style="color: black;">Welcome to iCheat</h1>
                                    <h3 style="color: black;">Sign Up</h3>
                                    <div class="callout-footer ml-lg-auto">
                                        <form id="register" method="post">
                                            <div class="input" style="padding-bottom: 5px;">
                                                <input type="text" name="name" class="form-control" placeholder="Name">
                                            </div>
                                            <div class="input" style="padding-bottom: 5px;">
                                                <input type="text" name="email" class="form-control"
                                                    placeholder="Email">
                                            </div>

                                            <div class="input" style="padding-bottom: 5px;">
                                                <input type="text" name="username" class="form-control"
                                                    placeholder="Username">
                                            </div>
                                            <div class="input" style="padding-bottom: 5px;">
                                                <input type="text" placeholder="Password" name="password"
                                                    class="form-control" data-role="tagsinput" required>
                                            </div>
                                            <div class="input" style="padding-bottom: 5px;">
                                                <select data-placeholder="Choose Account Type" name="accountType"
                                                    class="form-control" placeholder="Account type" style="width:100%">
                                                    <option value="" disabled selected>Select your position</option>
                                                    <option>Student</option>
                                                    <option>Professor</option>
                                                </select>
                                            </div>
                                            <div class="input" style="padding-bottom: 5px;">
                                                <input type="hidden" name="MAX_FILE_SIZE" value="512000" />
                                                <input name="userfile" type="file" />
                                            </div>
                                            <div class="input">
                                                <button type="submit" class="btn btn-primary float-right"
                                                    style="background-color: black; border-color:black;">Join
                                                    Today</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </section>
                        <!-- End of signup -->
                </div>
            </div>
        </div>
    </div>
</div>