<section class="products-background">
    <div class="span12 widget-span widget-type-cell">
        <div class="hsg-page-width-normal">
            <h1>Sign up now!</h1>
            <div class="callout-footer ml-lg-auto">
                <form id="myForm">
                    <div class="input">
                        <input type="text" name="name" class="form-control" placeholder="Name">
                    </div>
                    <div class="input">
                        <input type="text" name="email" class="form-control" placeholder="Email">
                    </div>
                    <!-- <div class="input">
                        <select multiple data-placeholder="Choose Business Type" data-init-plugin="select2" data-disable-search="true" name="type[]" class="form-control" placeholder="Business type" style="width:100%">
                            <option value=""></option>
                            <option>Restaurant</option>
                            <option>Ghost Kitchen operator</option>
                            <option>Caterer</option>
                            <option>Food Truck</option>
                            <option>Delivery Only</option>
                        </select>
                    </div> -->
                    <div class="input">
                        <input type="text" name="username" class="form-control" placeholder="Username">
                    </div>
                    <div class="input">
                        <input type="text" placeholder="Password" name="password" class="form-control"
                            data-role="tagsinput" required>
                    </div>
                    <div class="input">
                        <button type="submit" class="btn btn-primary float-right">Join Today</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>