<div class="d-flex justify-content-center full-height full-width align-items-center">
  <div class="error-container text-center">
    <h1 class="error-number">404</h1>
    <h2 class="light">Sorry but we couldnt find this page</h2>
    <p>This page you are looking for does not exsist <a href="#">Report this?</a>
    </p>
    <div class="error-container-innner text-center">
      <form>
        <div class="form-group form-group-default input-group transparent text-left">
          <label>Search</label>
          <input class="form-control" placeholder="Try searching the missing page" type="email"> <span class="input-group-addon pg-search"></span>
        </div>
      </form>
    </div>
  </div>
</div>