
<div class="vert-container">
    <menu type="toolbar" class="menu">
        <h2 class="menu-name" style="color:white; font-weight:bolder; font-size:20pt; font-family: Arial, Helvetica, sans-serif;">Profile</h2>
    </menu>

    <section class="chat" style="background-image: url('../../../assets/img/yupp.jpg');">
        
    <button id="leaveClass" class="btn btn-primary" style="background-color:black; border-color:black; margin-top: 10px;  margin-left: 25px;"><a href="/profile/edituser" style="color:white; font-family: Arial, Helvetica, sans-serif;">Edit User</a></button>
    </section>
</div>
</main>