<aside class="channels">
	<header class="channels-header focusable">
		<h3 role="header" class="channels-header-name" style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Notifications</h3>
		<svg role="button" aria-label="Dropdown" class="channels-header-dropdown">
			<use xlink:href="#icon-dropdown" /></svg>
	</header>

	<section class="channels-list">
		<header class="channels-list-header focusable">
			<a href="/notifications/messages">
				<h5 style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Messages</h5>
			</a>
		</header>
		<header class="channels-list-header focusable">
			<a href="/notifications/notify">
				<h5 style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Notifications</h5>
			</a>
		</header>
		<header class="channels-list-header focusable">
			<a href="/notifications/bids">
				<h5 style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Project Bids</h5>
			</a>
		</header>
	</section>

	<footer class="channels-footer">
		<img class="avatar" alt="Avatar" src="../../../assets/img/profilePictures/<?= $_SESSION['automatic_profile_pic']; ?>" />
		<div class="channels-footer-details">
			<span class="username"><?php echo $_SESSION['automatic_name'] ?></span>
			<span class="tag"></span>
		</div>
		<div class="channels-footer-controls button-group">

			<a href="/notifications">
				<button role="button" aria-label="Deafen" class="button button-deafen"><svg>
						<use xlink:href="#icon-deafen" />
					</svg></button>
			</a>
			<a href="/profile">
				<button role="button" aria-label="Settings" class="button button-settings"><svg>
						<use xlink:href="#icon-settings" />
					</svg></button>
			</a>
		</div>
	</footer>
</aside>

<div class="vert-container">
	<menu type="toolbar" class="menu">
		<h2 class="menu-name" id="menu-name" style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Notifications and Messages</h2>
	</menu>

	<section class="chat" style="background-image: url('../../../assets/img/yupp.jpg');">
		<div>
			<h1 style="color:black; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Project Bids</h1>
			<table>
				<tr style="background-color:black;">
					<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Project Name</th>
					<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Your asking Price</th>
					<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Bid Amount</th>
					<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Bid By</th>
					<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Date</th>
					<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Accept</th>
					<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Decline</th>
				</tr>

				<?php foreach ($this->projectBids as $bid) : ?>
					<tr style="background-color:black;">
						<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;"><?= $bid['projectname'] ?></th>
						<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;"><?= $bid['askingprice'] ?></th>
						<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;"><?= $bid['bid_amount'] ?></th>
						<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;"><?= $bid['name'] ?></th>
						<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;"><?= $bid['date'] ?></th>
						<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;"><a href="#" id="acceptBid" data-project-bid-id="<?= $bid['bid_id'] ?>">Accept</a></th>
						<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;"><a href="#" id="rejectBid" data-project-bid-id="<?= $bid['bid_id'] ?>">Decline</a></th>
					</tr>
				<?php endforeach; ?>
			</table>
		</div>

		<div>
			<h1 style="color:black; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Your Purchased Code</h1>
			<table>
				<tr style="background-color:black;">
					<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Project Name</th>
					<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Code</th>
					<th></th>
				</tr>
				<?php foreach ($this->projectCode as $code) : ?>
					<tr style="background-color:black;">
						<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;"><?= $code['projectname'] ?></th>
						<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;"><?= $code['content'] ?></th>
						<?php if ($code['review_left'] == 0) : ?>
							<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;"><a href="#" id="rateUser" data-toggle="modal" data-target="#rankModal" data-notification-id="<?= $code['bid_id'] ?>">Leave a review?</a></th>
						<?php endif; ?>

					</tr>
				<?php endforeach; ?>
			</table>
		</div>
	</section>
</div>
</main>

<div class="modal fade" id="rankModal" tabindex="-1" role="dialog" aria-labelledby="rankModal" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" style="color: black;" id="exampleModalLabel">New Message</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form id="leaveReviewForm">
					<div class="form-group form-group-default">
						<label style="color: black;">How clean was the users coding style?</label>
						<div class="controls">
							<select id="ranking1" name="ranking1" class="form-control">
								<option value="">Select Option</option>
								<option value="1">1</option>
								<option value="2">2</option>
								<option value="3">3</option>
								<option value="4">4</option>
								<option value="5">5</option>
							</select>
						</div>
					</div>
					<div class="form-group form-group-default">
						<label style="color: black;">How good was the code commented?</label>
						<div class="controls">
							<select id="ranking2" name="ranking2" class="form-control">
								<option value="">Select Option</option>
								<option value="1">1</option>
								<option value="2">2</option>
								<option value="3">3</option>
								<option value="4">4</option>
								<option value="5">5</option>
							</select>
						</div>
					</div>
					<div class="form-group form-group-default">
						<label style="color: black;">How close was the application to the project rubric?</label>
						<div class="controls">
							<select id="ranking3" name="ranking3" class="form-control">
								<option value="">Select Option</option>
								<option value="1">1</option>
								<option value="2">2</option>
								<option value="3">3</option>
								<option value="4">4</option>
								<option value="5">5</option>
							</select>
						</div>
					</div>
					<div class="form-group form-group-default">
						<label style="color: black;">What mark did you recive on the project?</label>
						<select id="grade" name="grade" class="form-control">
							<option value="">Select Option</option>
							<option value="1">0% - 19%</option>
							<option value="2">20% - 39%</option>
							<option value="3">40% - 59%</option>
							<option value="4">60% - 79%</option>
							<option value="5">80% - 100%</option>
						</select>
					</div>
					<div class="form-group form-group-default">
						<input type="hidden" id="idOfProject" name="idOfProject"  class="form-control" autocomplete="off"  value="">
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
						<button type="submit" class="btn btn-primary">Leave Review</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>