<aside class="channels">
	<header class="channels-header focusable">
		<h3 role="header" class="channels-header-name" style="color:white; font-weight:bolder; font-size:15pt; font-family: Arial, Helvetica, sans-serif;">Notifications</h3>
	</header>

	<section class="channels-list">
		<header class="channels-list-header focusable">
			<a href="/notifications/messages">
				<h5 style="color:white; font-weight:bolder; font-size:10pt; font-family: Arial, Helvetica, sans-serif;">Messages</h5>
			</a>
		</header>
		<header class="channels-list-header focusable">
			<a href="/notifications/notify">
				<h5 style="color:white; font-weight:bolder; font-size:10pt; font-family: Arial, Helvetica, sans-serif;">Notifications</h5>
			</a>
		</header>
		<header class="channels-list-header focusable">
			<a href="/notifications/bids">
				<h5 style="color:white; font-weight:bolder; font-size:10pt; font-family: Arial, Helvetica, sans-serif;">Project Bids</h5>
			</a>
		</header>
	</section>

	<footer class="channels-footer">
		<img class="avatar" alt="Avatar" src="../../../assets/img/profilePictures/<?= $_SESSION['automatic_profile_pic']; ?>" />
		<div class="channels-footer-details">
			<span class="username"><?php echo $_SESSION['automatic_name'] ?></span>
			<span class="tag"></span>
		</div>
		<div class="channels-footer-controls button-group">
			<a href="/notifications">
				<button role="button" aria-label="Deafen" class="button button-deafen"><svg>
						<use xlink:href="#icon-deafen" />
					</svg></button>
			</a>
			<a href="/profile">
				<button role="button" aria-label="Settings" class="button button-settings"><svg>
						<use xlink:href="#icon-settings" />
					</svg></button>
			</a>
		</div>
	</footer>
</aside>

<div class="vert-container">
	<menu type="toolbar" class="menu">
		<h2 class="menu-name" id="menu-name" style="color:white; font-weight:bolder; font-size:15pt; font-family: Arial, Helvetica, sans-serif;">Notifications and Messages</h2>
	</menu>

	
<div class="notify"></div>

	<section class="chat" style="background-image: url('../../../assets/img/yupp.jpg');">
		<div>
			<h1 style="color:black; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">New Messages</h1>
			<table>
				<tr style="background-color:black;">
					<th style="color:white; background-color:black; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Subject</th>
					<th style="color:white; background-color:black; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Message</th>
					<!-- <th>Sender</th> -->
					<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Date Sent</th>
					<th></th>
				</tr>

				<?php foreach ($this->messages as $notify) : ?>
					<tr style="background-color:black;">
						<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;" <?php echo "onclick='()'" ?>> <?= $notify['type'] ?></th>
						<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;"><?= $notify['message'] ?></th>

						<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;"><?= $notify['date'] ?></th>
						<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;"><a href="#" id="markMessageAsRead" data-message-id="<?= $notify['id'] ?>">Mark as read</a></th>
					</tr>
				<?php endforeach; ?>
			</table>
		</div>
		<div>
			<h1  style="color:black; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Old Messages</h1>
			<table>
				<tr style="background-color:black;">
					<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Subject</th>
					<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Message</th>
					<!-- <th>Sender</th> -->
					<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Date Sent</th>
				</tr>
				<?php foreach ($this->messagesRead as $notify) : ?>
					<tr style="background-color:black;">
						<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;"><?= $notify['type'] ?></th>
						<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;"><?= $notify['message'] ?></th>

						<th style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;"><?= $notify['date'] ?></th>
					</tr>
				<?php endforeach; ?>
			</table>
		</div>
		<div class="input">
			<button type="submit" class="btn btn-primary float-right" data-toggle="modal" data-target="#exampleModal" style="background-color: black; border-color:black; color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif; margin-top:10px;">New Message/Alert</button>
		</div>
	</section>
</div>
</main>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" style="color:black; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;" id="exampleModalLabel">New Message</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form id="createMsg">
					<div class="form-group form-group-default">
						<label style="color:black; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Subject</label>
						<div class="controls">
							<input type="text" id="type" name="type" placeholder="Subject" class="form-control" autocomplete="off" required>
						</div>
					</div>
					<div class="form-group form-group-default">
						<label style="color:black; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Message</label>
						<div class="controls">
							<input type="text" id="message" name="message" placeholder="Message" class="form-control" autocomplete="off" required>
						</div>
					</div>
					<div class="form-group form-group-default">
						<label style="color:black; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Send To</label>
						<!-- <div class="controls">
							<input type="text" id="userid" name="userid" placeholder="Send To" class="form-control" autocomplete="off" required>
						</div> -->
						<select id="userid" name="userid" class="form-control" > <!-- style="width: 100%; margin-bottom:10px;" -->
							<?php foreach ($this->users as $user) : ?>
								<option value="<?= $user['id']; ?>" data-user-id="<?= $user['id']; ?>"> <?= $user['name']; ?> </option>
							<?php endforeach; ?>
						</select>
						
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal" style="color:white; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Close</button>
						<button type="submit" class="btn btn-primary" style="color:white; background-color:black; border-color:black; font-weight:bolder; font-family: Arial, Helvetica, sans-serif;">Send Message</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>